version: '3.1'
services:
  # api-server:
  #   image: asyncfiber:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env.prod
  #   restart: always
  #   command: "./bin/exe s"
  #   networks:
  #     - asyncfiber_network
  #   ports:
  #     - 8000:8000

  # worker:
  #   image: asyncfiber:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env.prod
  #   restart: always
  #   networks:
  #     - asyncfiber_network
  #   command: "./bin/exe w"

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - asyncfiber_network
    command: /bin/sh -c "redis-server --requirepass password"
    environment:
      - REDIS_HOST_PASSWORD=password
    volumes:
      - ./data/redis:/data

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: hpcc_checkin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_USER: admin
  #   ports:
  #     - 5432:5432
  #   restart: on-failure:3
  #   networks:
  #     - asyncfiber_network
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

networks:
  asyncfiber_network:
volumes:
  data: